export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ZONE_SUMMARY_SUCCESS = "ZONE_SUMMARY_SUCCESS";
export const ZONE_SUMMARY_FAIL = "ZONE_SUMMARY_FAIL";
export const ZONE_SUMMARY_START = "ZONE_SUMMARY_START";

export const RELEASE_QUEUE_FETCH_START = "RELEASE_QUEUE_FETCH_START";
export const RELEASE_QUEUE_FETCH_SUCCESS = "RELEASE_QUEUE_FETCH_SUCCESS";
export const RELEASE_QUEUE_FETCH_FAIL = "RELEASE_QUEUE_FETCH_FAIL";

export const UPCOMING_RELEASES_FETCH_START = "UPCOMING_RELEASES_FETCH_START";
export const UPCOMING_RELEASES_FETCH_SUCCESS = "UPCOMING_RELEASES_FETCH_SUCCESS";
export const UPCOMING_RELEASES_FETCH_FAIL = "UPCOMING_RELEASES_FETCH_FAIL";